import { afterEach, expect, it, vi } from 'vitest'
import { aiRecoveryTimeoutSeconds, createAiResponseParser, defaultSettings, polishText } from './ai-polish'
const settings = { ...defaultSettings, apiKey: 'test-key', timeoutSeconds: 600 }
const answer = (content = 'Complete answer') => ({ status: 200, statusText: 'OK', body: JSON.stringify({ choices: [{ message: { content }, finish_reason: 'stop' }] }) })
const error = (message: string) => ({ status: 400, statusText: 'Bad Request', body: JSON.stringify({ error: { message } }) })
afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks(); vi.unstubAllGlobals() })

it('lets reasoning use the full configured timeout and gives recovery its own larger deadline', async () => {
  expect(aiRecoveryTimeoutSeconds(600)).toBe(1200)
  expect(aiRecoveryTimeoutSeconds(3600)).toBe(7200)
  vi.useFakeTimers()
  const aiRequest = vi.fn(async () => { await new Promise(resolve => setTimeout(resolve, 550_000)); return answer() })
  vi.stubGlobal('window', { desktop: { aiRequest } })
  const pending = polishText(settings, 'Review', 'Source')
  await vi.advanceTimersByTimeAsync(550_000)
  expect(await pending).toBe('Complete answer')
  expect(aiRequest.mock.calls).toHaveLength(1)
})
it('recovers Thinking incompatibility in steps and can opt out', async () => {
  const aiRequest = vi.fn().mockResolvedValueOnce(error('thinking adaptive is not supported')).mockResolvedValueOnce(error('thinking is unsupported')).mockResolvedValue(answer())
  vi.stubGlobal('window', { desktop: { aiRequest } })
  const progress = vi.fn()
  await polishText({ ...settings, provider: 'claude', model: 'claude-sonnet-4-6' }, 'Review', 'Source', progress)
  const bodies = aiRequest.mock.calls.map(([request]) => JSON.parse(request.body))
  expect(bodies[0].thinking.type).toBe('adaptive')
  expect(bodies[1].thinking).toMatchObject({ type: 'enabled' })
  expect(bodies[2].thinking).toBeUndefined()
  expect(progress.mock.calls.some(([value]) => value.recovery?.action === 'thinking')).toBe(true)
  aiRequest.mockReset().mockResolvedValue(error('thinking is unsupported'))
  await expect(polishText({ ...settings, provider: 'claude', model: 'claude-sonnet-4-6', allowThinkingFallback: false }, 'Review', 'Source')).rejects.toThrow('400')
  expect(aiRequest).toHaveBeenCalledOnce()
})
it('fits a provider output limit while reserving final-answer room for manual Thinking', async () => {
  const aiRequest = vi.fn().mockResolvedValueOnce(error('max_tokens must be at most 8192')).mockResolvedValue(answer())
  vi.stubGlobal('window', { desktop: { aiRequest } })
  await polishText({ ...settings, provider: 'claude', model: 'claude-sonnet-4-5', thinking: 'enabled', thinkingBudget: 60000 }, 'Review', 'Source')
  const payload = JSON.parse(aiRequest.mock.calls[1][0].body)
  expect(payload.max_tokens).toBe(8192)
  expect(payload.thinking.budget_tokens).toBe(7168)
  aiRequest.mockReset().mockResolvedValue(error('max_tokens must be at most 1024'))
  await expect(polishText({ ...settings, provider: 'claude', thinking: 'enabled', allowThinkingFallback: false }, 'Review', 'Source')).rejects.toThrow('aiSettings.thinkingBudgetConflict')
  expect(aiRequest).toHaveBeenCalledOnce()
})
it('recovers reasoning-only truncation at the service ceiling without returning partial text', async () => {
  const aiRequest = vi.fn().mockResolvedValueOnce(error('max_tokens must be at most 8192')).mockResolvedValueOnce({ status: 200, body: JSON.stringify({ choices: [{ message: { reasoning_content: 'Thinking'.repeat(500), content: '' }, finish_reason: 'length' }] }) }).mockResolvedValue(answer())
  vi.stubGlobal('window', { desktop: { aiRequest } })
  expect(await polishText({ ...settings, provider: 'deepseek', thinking: 'enabled' }, 'Review', 'Source')).toBe('Complete answer')
  expect(JSON.parse(aiRequest.mock.calls[2][0].body)).toMatchObject({ max_tokens: 8192, thinking: { type: 'disabled' } })
})
it('retries HTTP-200 error events and broken streams instead of accepting partial output', async () => {
  vi.useFakeTimers()
  const aiRequest = vi.fn().mockResolvedValueOnce({ status: 200, body: 'data: {"choices":[{"delta":{"content":"partial"}}]}\n\n' }).mockResolvedValueOnce({ status: 200, body: 'event: error\ndata: {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}\n\n' }).mockResolvedValue(answer())
  vi.stubGlobal('window', { desktop: { aiRequest } })
  const pending = polishText(settings, 'Review', 'Source')
  await vi.runAllTimersAsync()
  expect(await pending).toBe('Complete answer')
  expect(aiRequest).toHaveBeenCalledTimes(3)
})
it('parses split Unicode, multiline data and thousands of Thinking events without duplication', () => {
  const parser = createAiResponseParser()
  const body = Array.from({ length: 2000 }, () => 'data: {"choices":[{"delta":{"reasoning_content":"考😀"}}]}\r\n\r\n').join('') + 'data: {"choices":\ndata: [{"delta":{"content":"回答 한국어 العربية"},"finish_reason":"stop"}]}\n\n'
  for (let i = 0; i < body.length; i += 13) parser.push(body.slice(i, i + 13))
  const result = parser.finish()
  expect(result.reasoning).toBe('考😀'.repeat(2000))
  expect(result.output).toBe('回答 한국어 العربية')
  expect(parser.complete).toBe(true)
  expect(parser.failure).toBeUndefined()
})
